### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by AndreasLoow** [5j9/yadkard#5]
The generated citation for DOI 10.1007/bf02276799 has some encoding errors:

> {{cite journal | last=Schwichtenberg | first=Helmut | title=Definierbare Funktionen im$\uplambda$-KalkĂźl mit Typen | journal=Archiv fĂźr Mathematische Logik und Grundlagenforschung | publisher=Springer Nature | volume=17 | issue=3-4 | year=1975 | pages=113–114 | url=https://doi.org/10.1007%2Fbf02276799 | doi=10.1007/bf02276799 | ref=harv | accessdate=May 21, 2017}}

Note e.g. the field "journal", which is strange, because DOI 10.1007/bf02276805, from the same journal, works:

> {{cite journal | last=Schütte | first=Kurt | title=Einführung der Normalfunktionen$upTheta$ a ohne Auswahlaxiom und ohne Regularitätsbedingungohne Auswahlaxiom und ohne Regularitätsbedingung | journal=Archiv für Mathematische Logik und Grundlagenforschung | publisher=Springer Nature | volume=17 | issue=3-4 | year=1975 | pages=171–178 | url=https://doi.org/10.1007%2Fbf02276805 | doi=10.1007/bf02276805 | ref=harv | accessdate=May 21, 2017}}

**Comment by 5j9** [comment]
This should be resolved now.
