### ISSUE TITLE
books.google.co.uk

### ISSUE THREAD

**Issue by daniel-barrows** [5j9/yadkard#8]
Both of these links point to the same book:
https://books.google.co.uk/books?id=zOm0iqkRsYEC&pg=PA254
https://books.google.com/books?id=zOm0iqkRsYEC&pg=PA254
Yadkard only works well with the second, treating the first like any other website. I would suggest normalizing all URLs at the domain books.google.co.uk to books.google.com, and then processing them as usual Google Books citations.

**Comment by 5j9** [comment]
Thanks for reporting this issue. The fix will be deployed soon. It also covers other Google Books domains like https://books.google.co.vi/ .
